
package com.nantian.test1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Data", targetNamespace = "http://data.nantian.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Data {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://data.nantian.com/", className = "com.nantian.test1.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://data.nantian.com/", className = "com.nantian.test1.AddResponse")
    @Action(input = "http://data.nantian.com/Data/addRequest", output = "http://data.nantian.com/Data/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "min", targetNamespace = "http://data.nantian.com/", className = "com.nantian.test1.Min")
    @ResponseWrapper(localName = "minResponse", targetNamespace = "http://data.nantian.com/", className = "com.nantian.test1.MinResponse")
    @Action(input = "http://data.nantian.com/Data/minRequest", output = "http://data.nantian.com/Data/minResponse")
    public int min(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
