
package com.nantian.client3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Igtjtservice", targetNamespace = "http://service.interf.gtjt.cux/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Igtjtservice {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importAPUNINV", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPUNINV")
    @ResponseWrapper(localName = "importAPUNINVResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPUNINVResponse")
    public String importAPUNINV(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importARcustomer", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportARcustomer")
    @ResponseWrapper(localName = "importARcustomerResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportARcustomerResponse")
    public String importARcustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importGlJe", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportGlJe")
    @ResponseWrapper(localName = "importGlJeResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportGlJeResponse")
    public String importGlJe(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importAPINV", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPINV")
    @ResponseWrapper(localName = "importAPINVResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPINVResponse")
    public String importAPINV(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importAPuncheck", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPuncheck")
    @ResponseWrapper(localName = "importAPuncheckResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPuncheckResponse")
    public String importAPuncheck(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importAPunpre", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPunpre")
    @ResponseWrapper(localName = "importAPunpreResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPunpreResponse")
    public String importAPunpre(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "querycashflowdata", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.Querycashflowdata")
    @ResponseWrapper(localName = "querycashflowdataResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.QuerycashflowdataResponse")
    public String querycashflowdata(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importFa", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportFa")
    @ResponseWrapper(localName = "importFaResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportFaResponse")
    public String importFa(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryinfo", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.Queryinfo")
    @ResponseWrapper(localName = "queryinfoResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.QueryinfoResponse")
    public String queryinfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importAPvendor", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPvendor")
    @ResponseWrapper(localName = "importAPvendorResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPvendorResponse")
    public String importAPvendor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "querycashflowdatain", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.Querycashflowdatain")
    @ResponseWrapper(localName = "querycashflowdatainResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.QuerycashflowdatainResponse")
    public String querycashflowdatain(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryaccountingtra", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.Queryaccountingtra")
    @ResponseWrapper(localName = "queryaccountingtraResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.QueryaccountingtraResponse")
    public String queryaccountingtra(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importAPpre", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPpre")
    @ResponseWrapper(localName = "importAPpreResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPpreResponse")
    public String importAPpre(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "querytimeacctamount", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.Querytimeacctamount")
    @ResponseWrapper(localName = "querytimeacctamountResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.QuerytimeacctamountResponse")
    public String querytimeacctamount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryrevaluationrate", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.Queryrevaluationrate")
    @ResponseWrapper(localName = "queryrevaluationrateResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.QueryrevaluationrateResponse")
    public String queryrevaluationrate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importCOAinfo", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportCOAinfo")
    @ResponseWrapper(localName = "importCOAinfoResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportCOAinfoResponse")
    public String importCOAinfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryaccountbalance", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.Queryaccountbalance")
    @ResponseWrapper(localName = "queryaccountbalanceResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.QueryaccountbalanceResponse")
    public String queryaccountbalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     * @throws UnsupportedEncodingException_Exception
     * @throws ConfigurationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importAPcheck", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPcheck")
    @ResponseWrapper(localName = "importAPcheckResponse", targetNamespace = "http://service.interf.gtjt.cux/", className = "com.nantian.client3.ImportAPcheckResponse")
    public String importAPcheck(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConfigurationException_Exception, SQLException_Exception, UnsupportedEncodingException_Exception
    ;

}
