
package com.nantian.test2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Data", targetNamespace = "http://data.nantian.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Data {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://data.nantian.com/", className = "com.nantian.test2.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://data.nantian.com/", className = "com.nantian.test2.AddResponse")
    @Action(input = "http://data.nantian.com/Data/addRequest", output = "http://data.nantian.com/Data/addResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "minResult", targetNamespace = "")
    @RequestWrapper(localName = "min", targetNamespace = "http://data.nantian.com/", className = "com.nantian.test2.Min")
    @ResponseWrapper(localName = "minResponse", targetNamespace = "http://data.nantian.com/", className = "com.nantian.test2.MinResponse")
    @Action(input = "http://data.nantian.com/Data/minRequest", output = "http://data.nantian.com/Data/minResponse")
    public int min(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
