package com.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-13T17:27:30.508+08:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "DataImplService",
                  wsdlLocation = "http://localhost:9090/service?wsdl",
                  targetNamespace = "http://daoImpl.nantian.com/")
public class DataImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://daoImpl.nantian.com/", "DataImplService");
    public final static QName DataImplPort = new QName("http://daoImpl.nantian.com/", "DataImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/service?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DataImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/service?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DataImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DataImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DataImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DataImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DataImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Data
     */
    @WebEndpoint(name = "DataImplPort")
    public Data getDataImplPort() {
        return super.getPort(DataImplPort, Data.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Data
     */
    @WebEndpoint(name = "DataImplPort")
    public Data getDataImplPort(WebServiceFeature... features) {
        return super.getPort(DataImplPort, Data.class, features);
    }

}
