package com.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-13T17:27:30.464+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://dao.nantian.com/", name = "Data")
@XmlSeeAlso({ObjectFactory.class})
public interface Data {

    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://dao.nantian.com/", className = "com.service.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://dao.nantian.com/", className = "com.service.DeleteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int delete(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "select1", targetNamespace = "http://dao.nantian.com/", className = "com.service.Select1")
    @ResponseWrapper(localName = "select1Response", targetNamespace = "http://dao.nantian.com/", className = "com.service.Select1Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.service.Student select1(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://dao.nantian.com/", className = "com.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://dao.nantian.com/", className = "com.service.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.service.Student arg0
    );

    @WebMethod
    @RequestWrapper(localName = "select2", targetNamespace = "http://dao.nantian.com/", className = "com.service.Select2")
    @ResponseWrapper(localName = "select2Response", targetNamespace = "http://dao.nantian.com/", className = "com.service.Select2Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String select2(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
